INSERT  INTO
	jp_demo_order_main
      ( 
      ID                            
      ,CREATE_DT                      
      ,CRTUSER                        
      ,CRTUSER_NAME                   
      ,DEL_DT                         
      ,DELFLAG                        
      ,GO_ALL_PRICE                   
      ,GO_CONTACT_NAME                
      ,GO_CONTENT                     
      ,GO_ORDER_CODE                  
      ,GO_ORDER_COUNT                 
      ,GO_RETURN_PRICE                
      ,GO_TELPHONE                    
      ,GODER_TYPE                     
      ,MODIFIER                       
      ,MODIFIER_NAME                  
      ,MODIFY_DT                      
      ,USERTYPE                       
      ) 
values
      (
      :jpDemoOrderMain.id                            
      ,:jpDemoOrderMain.createDt                      
      ,:jpDemoOrderMain.crtuser                       
      ,:jpDemoOrderMain.crtuserName                   
      ,:jpDemoOrderMain.delDt                         
      ,:jpDemoOrderMain.delflag                       
      ,:jpDemoOrderMain.goAllPrice                    
      ,:jpDemoOrderMain.goContactName                 
      ,:jpDemoOrderMain.goContent                     
      ,:jpDemoOrderMain.goOrderCode                   
      ,:jpDemoOrderMain.goOrderCount                  
      ,:jpDemoOrderMain.goReturnPrice                 
      ,:jpDemoOrderMain.goTelphone                    
      ,:jpDemoOrderMain.goderType                     
      ,:jpDemoOrderMain.modifier                      
      ,:jpDemoOrderMain.modifierName                  
      ,:jpDemoOrderMain.modifyDt                      
      ,:jpDemoOrderMain.usertype                      
      )