INSERT  INTO
	jp_demo_order_custom
      ( 
      ID                            
      ,CREATE_DT                      
      ,CRTUSER                        
      ,CRTUSER_NAME                   
      ,DEL_DT                         
      ,DELFLAG                        
      ,GO_ORDER_CODE                  
      ,GOC_BUSS_CONTENT               
      ,GOC_CONTENT                    
      ,GOC_CUS_NAME                   
      ,GOC_IDCARD                     
      ,GOC_PASSPORT_CODE              
      ,GOC_SEX                        
      ,MODIFIER                       
      ,MODIFIER_NAME                  
      ,MODIFY_DT                      
      ) 
values
      (
      :jpDemoOrderCustom.id                            
      ,:jpDemoOrderCustom.createDt                      
      ,:jpDemoOrderCustom.crtuser                       
      ,:jpDemoOrderCustom.crtuserName                   
      ,:jpDemoOrderCustom.delDt                         
      ,:jpDemoOrderCustom.delflag                       
      ,:jpDemoOrderCustom.goOrderCode                   
      ,:jpDemoOrderCustom.gocBussContent                
      ,:jpDemoOrderCustom.gocContent                    
      ,:jpDemoOrderCustom.gocCusName                    
      ,:jpDemoOrderCustom.gocIdcard                     
      ,:jpDemoOrderCustom.gocPassportCode               
      ,:jpDemoOrderCustom.gocSex                        
      ,:jpDemoOrderCustom.modifier                      
      ,:jpDemoOrderCustom.modifierName                  
      ,:jpDemoOrderCustom.modifyDt                      
      )