INSERT  INTO
	jp_demo_order_product
      ( 
      ID                            
      ,CREATE_DT                      
      ,CRTUSER                        
      ,CRTUSER_NAME                   
      ,DEL_DT                         
      ,DELFLAG                        
      ,GO_ORDER_CODE                  
      ,GOP_CONTENT                    
      ,GOP_COUNT                      
      ,GOP_ONE_PRICE                  
      ,GOP_PRODUCT_NAME               
      ,GOP_PRODUCT_TYPE               
      ,GOP_SUM_PRICE                  
      ,MODIFIER                       
      ,MODIFIER_NAME                  
      ,MODIFY_DT                      
      ) 
values
      (
      :jpDemoOrderProduct.id                            
      ,:jpDemoOrderProduct.createDt                      
      ,:jpDemoOrderProduct.crtuser                       
      ,:jpDemoOrderProduct.crtuserName                   
      ,:jpDemoOrderProduct.delDt                         
      ,:jpDemoOrderProduct.delflag                       
      ,:jpDemoOrderProduct.goOrderCode                   
      ,:jpDemoOrderProduct.gopContent                    
      ,:jpDemoOrderProduct.gopCount                      
      ,:jpDemoOrderProduct.gopOnePrice                   
      ,:jpDemoOrderProduct.gopProductName                
      ,:jpDemoOrderProduct.gopProductType                
      ,:jpDemoOrderProduct.gopSumPrice                   
      ,:jpDemoOrderProduct.modifier                      
      ,:jpDemoOrderProduct.modifierName                  
      ,:jpDemoOrderProduct.modifyDt                      
      )