INSERT  INTO
	cms_ad
      ( 
      id                            
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,title                          
      ,image_href                     
      ) 
values
      (
      :cmsAd.id                            
      ,:cmsAd.createName                    
      ,:cmsAd.createBy                      
      ,:cmsAd.createDate                    
      ,:cmsAd.title                         
      ,:cmsAd.imageHref                     
      )